version: '3'

vars:
  USAGE: |
    Usage:
      task <task> [LANG=<lang>] [MODE=<mode>]

    LANG is one of:
      c (default)
      cpp

    NOTE: LANG is only used for the MSVC build.

    MODE is one of:
      debug (default)
      release

env:
  # Directories
  SRC: src
  OBJ: obj
  BIN: bin
  MODE: debug
  LANG: cpp

# https://taskfile.dev/usage/#including-other-taskfiles
includes:
  msvc:
    taskfile: MsvcTasks.yml
    vars:
      SRC: '{{.SRC}}/{{.LANG}}'
      EXT_SOURCE: '{{.LANG}}'
      # Ugly but need due to significant whitespace because screw you. See:
      #   https://yaml-multiline.info/
      EXT_HEADER: >-
        {{if eq .LANG "cpp"}}{{"hpp"}}{{else if eq .LANG "c"}}{{"h"}}
        {{else}}
        {{fail "LANG must be one of `c cpp`"}}
        {{end}}
      OUT_EXE: '{{.BIN}}/msvc-out{{exeExt}}'

  odin:
    taskfile: OdinTasks.yml
    vars:
      SRC: '{{.SRC}}/odin'
      OUT_EXE: '{{.BIN}}/odin-out{{exeExt}}'
      TEST_EXE: '{{.BIN}}/odin-test{{exeExt}}'

# Note:
#   Unlike GNU Make, we need to explicitly specify as default task when no
#   label is specified.
#
# See:
#   https://taskfile.dev/usage/#getting-started
#   https://taskfile.dev/reference/templating/#built-in-functions
tasks:
  default:
    cmds:
      - task: usage
  
  usage:
    silent: true
    cmds:
      - |
        printf '{{.USAGE}}'
        task --list
  
  dirs: mkdir -p {{.OBJ}} {{.BIN}}

  cleanup: rm -rf {{.OBJ}} {{.BIN}}
